### PR TITLE
new seekbar option to prevent label overlap

### PR DESCRIPTION
**Pull request by oberhamsi**
potential fix for https://github.com/bitmovin/bitmovin-player-ui/issues/569

### CODE REVIEW

**Comment by felix-hoc** [comment]
Thanks for the submission! :) I tested it a bit - unfortunately, the thumbnails seem to jump around wildly when getting close to the edges, and also the arrow disappears: 
[Screencast.webm](https://github.com/bitmovin/bitmovin-player-ui/assets/16101788/e3439daa-ba99-45d2-bbf0-262576e190ab)

I think we need to find a different solution.

**Comment by oberhamsi** [comment]
wouldn't call it "wildly" ;) it moves inside so it doesn't overlap. any suggestions on a direction to take on this?

**Comment by felix-hoc** [comment]
Yeah I get that :) From a user perspective, it would be nice if the thumbnail would simply stop moving out of the frame, so it stays "attached" to the left/right edge when the mouse moves further out.

I had a quick look but also couldn't come up with a better solution so far :/ we'll need to properly look into it.

**Comment by oberhamsi** [comment]
i think i addressed both your concerns - the label now stays at the edge (with a bit of margin) instead of jumping away from it and the arrow keeps indicating the visible position

[Screencast from 2024-02-28 13:09:31.webm](https://github.com/bitmovin/bitmovin-player-ui/assets/53384/173b6715-4d4d-41ba-8572-ae7cc1ade040)

**Comment by oberhamsi** [comment]
any news on this? if you are worried about performance, i could throttle the overflow-prevention.

**Comment by felix-hoc** [comment]
Sorry for the delay! We have spent some time on it and fixed it here: https://github.com/bitmovin/bitmovin-player-ui/pull/661

We took inspiration from your PR and made some adjustments to hopefully reduce the performance impact. We also made this the default behavior.

**Comment by oberhamsi** [comment]
i tested it with v3.76 and works great for us, cheers!

**Pull request closed without merging**
