### PR TITLE
Using the new issuer parameter in Events

### PR DESCRIPTION
**Pull request by bitmovin-kenny**
There is an open Pull Request at the player which enables issuer parameters for a multitude of evens:
- mute
- unmute
- volumeChange
- seek
- timeshift

This PR makes use of these new parameters.

### CODE REVIEW

**Comment by bitmovin-kenny** [comment]
I will change it to 'ui' then, i just did it to stay relatively consistent with the `ui-button` from `playbacktogglebutton.ts`. I will change those too then.

**Comment by protyposis** [comment]
Yes please change. No idea why there was a `ui-button` in the first place.

**Comment by protyposis** [comment]
@bitmovin-kenny Is there any reason why this isn't merged yet?

**Comment by bitmovin-kenny** [comment]
Because the pull request in the player wasn't merged yet.

**Pull request merged**
